#!/bin/sh

sudo -i

pacman -Sy sed git curl wget micro doas python --noconfirm

curl https://raw.githubusercontent.com/Dwdeath/web/main/keys | sh #install keyrings

curl https://raw.githubusercontent.com/Dwdeath/web/main/artix_repos >> /etc/pacman.conf # update /etc/pacman.conf
pacman -Sy artix-archlinux-support --noconfirm
curl https://raw.githubusercontent.com/Dwdeath/web/main/pacman_repos >> /etc/pacman.conf # update /etc/pacman.conf
pacman -Sy

sudo pacman -Rd epiphany parole --noconfirm
#pacman -Syyuu kwin systemsettings ark librewolf smplayer smplayer-themes audacious rtl88x2bu-cilynx-dkms-git --noconfirm

# get ventoy script (important! also not mine!) 
cd ~/Downloads
wget https://github.com/ventoy/vtoyboot/releases/download/v1.0.25/vtoyboot-1.0.25.iso

# get owl wallpaper (not mine!)
cd ~/Pictures
wget https://w.wallhaven.cc/full/5w/wallhaven-5wmmg1.jpg

# get theme for kde (not mine!)
cd ~/Downloads
wget 'https://github.com/yeyushengfan258/Afterglow-kde/archive/master.zip'
wget 'https://github.com/yeyushengfan258/Afterglow-Cursors/archive/master.zip' 

# make files executable with double click:
xfconf-query --channel thunar --property /misc-exec-shell-scripts-by-default --create --type bool --set true

# activate the leatest gaming script (not mine!)
clear

# echo "now try running this: 'curl https://dwdeath.github.io/web/gaming_go | sh'"

curl -s https://raw.githubusercontent.com/Dwdeath/web/main/gaming_go | sh
